"""drop app_settings table

Revision ID: 622503188e18
Revises: 894c05a6a4d9
Create Date: 2026-03-12 19:15:28.846428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '622503188e18'
down_revision: Union[str, Sequence[str], None] = '894c05a6a4d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_settings')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('setting_key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('setting_value', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('app_settings_pkey')),
    sa.UniqueConstraint('setting_key', name=op.f('app_settings_setting_key_key'))
    )
    # ### end Alembic commands ###
