"""Initial migration

Revision ID: 894c05a6a4d9
Revises: 
Create Date: 2026-01-27 14:43:53.718820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '894c05a6a4d9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_settings', sa.Column('setting_key', sa.String(length=100), nullable=False))
    op.add_column('app_settings', sa.Column('setting_value', sa.String(length=500), nullable=True))
    op.drop_constraint(op.f('unique_setting_per_app'), 'app_settings', type_='unique')
    op.create_unique_constraint(None, 'app_settings', ['setting_key'])
    op.drop_column('app_settings', 'selected_model')
    op.drop_column('app_settings', 'app_type')
    op.drop_column('app_settings', 'setting_id')
    op.drop_column('app_settings', 'selected_document_type')
    op.drop_column('app_settings', 'selected_department')
    op.drop_column('app_settings', 'selected_doctor')
    op.alter_column('prompts', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('summary_usage', 'app_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('summary_usage', 'processing_time',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.create_index('ix_summary_usage_date_document_type', 'summary_usage', ['date', 'document_types'], unique=False)
    op.drop_column('summary_usage', 'total_tokens')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('summary_usage', sa.Column('total_tokens', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index('ix_summary_usage_date_document_type', table_name='summary_usage')
    op.alter_column('summary_usage', 'processing_time',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('summary_usage', 'app_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('prompts', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.add_column('app_settings', sa.Column('selected_doctor', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('app_settings', sa.Column('selected_department', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('app_settings', sa.Column('selected_document_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('app_settings', sa.Column('setting_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('app_settings', sa.Column('app_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('app_settings', sa.Column('selected_model', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'app_settings', type_='unique')
    op.create_unique_constraint(op.f('unique_setting_per_app'), 'app_settings', ['setting_id', 'app_type'])
    op.drop_column('app_settings', 'setting_value')
    op.drop_column('app_settings', 'setting_key')
    # ### end Alembic commands ###
